version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DJANGO_SETTINGS_MODULE=league_manager.settings
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - static_volume:/app/staticfiles
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/scheduler/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    command: sh -c "uv run python manage.py migrate && uv run python manage.py collectstatic --noinput && uv run gunicorn --bind 0.0.0.0:8001 --workers 3 --access-logfile - --error-logfile - --log-level info league_manager.wsgi:application"

  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-scheduler_db}
      - POSTGRES_USER=${POSTGRES_USER:-scheduler_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:

networks:
  default:
    external: true
    name: shared-network