[project]
name = "usbf-schedule"
version = "0.1.0"
description = "A basketball league schedule generator"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.3",
    "django-webpack-loader>=3.2.1",
    "icalendar>=6.3.1",
    "pulp>=3.2.2",
]
