# Generated by Django 5.1.6 on 2025-04-13 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="season",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="season",
            name="start_date",
        ),
    ]
