# Generated by Django 5.2.3 on 2025-08-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamorganization',
            name='name',
            field=models.CharField(help_text='Team name that persists across seasons', max_length=100),
        ),
    ]
