# Generated by Django 5.1.6 on 2025-02-25 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw_schedule_data", models.JSONField()),
                ("complete_schedule_data", models.JSONField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="game",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games",
                to="scheduler.savedschedule",
            ),
        ),
    ]
