# Generated by Django 5.2.3 on 2025-08-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_teamorganization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Marks this season as soft-deleted (hidden from normal queries)'),
        ),
    ]
