# Generated by Django 5.1.6 on 2025-04-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0002_remove_season_end_date_remove_season_start_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="game",
            options={"ordering": ["week", "level"]},
        ),
        migrations.RemoveField(
            model_name="game",
            name="slot",
        ),
        migrations.AlterField(
            model_name="level",
            name="name",
            field=models.CharField(
                help_text="e.g., Mid, High, Top, etc.", max_length=50
            ),
        ),
    ]
