# Generated by Django 5.2.3 on 2025-08-18 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_season_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamorganization',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Marks this team as soft-deleted (hidden from normal queries)'),
        ),
    ]
