# Generated by Django 5.1.6 on 2025-04-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0003_alter_game_options_remove_game_slot_alter_level_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Designates this season as the currently active one (only one can be active).",
            ),
        ),
        migrations.AddConstraint(
            model_name="season",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("is_active",),
                name="unique_active_season",
            ),
        ),
    ]
