# Generated by Django 5.2.3 on 2025-08-23 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_teamorganization_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offweek',
            name='description',
            field=models.TextField(default='', help_text="Description of what's happening this week (e.g., 'Charity Tournament', 'Holiday Break')"),
        ),
    ]
