# Generated by Django 5.1.6 on 2025-04-14 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0004_season_is_active_season_unique_active_season"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="referee_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="games_as_referee",
                to="scheduler.team",
            ),
        ),
    ]
