# Generated by Django 5.2 on 2025-04-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler", "0005_alter_game_referee_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="game",
            name="referee_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
