# Generated by Django 5.2.3 on 2025-08-23 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_alter_offweek_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='season_team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team1', to='scheduler.seasonteam'),
        ),
        migrations.AlterField(
            model_name='game',
            name='season_team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games_as_team2', to='scheduler.seasonteam'),
        ),
        migrations.AlterField(
            model_name='game',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='scheduler.week'),
        ),
    ]
