# Generated by Django 5.1.6 on 2025-05-10 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0006_game_referee_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="game",
            name="date_time",
        ),
        migrations.AddField(
            model_name="game",
            name="day_of_week",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="game",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="OffWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monday_date", models.DateField()),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="off_weeks",
                        to="scheduler.season",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveIntegerField()),
                ("monday_date", models.DateField()),
                (
                    "season",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="scheduler.season",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="game",
            name="week",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="games",
                to="scheduler.week",
            ),
        ),
    ]
