# Generated by Django 5.1.6 on 2025-05-10 19:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("scheduler", "0007_remove_game_date_time_game_day_of_week_game_time_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="offweek",
            unique_together={("season", "monday_date")},
        ),
        migrations.AlterUniqueTogether(
            name="week",
            unique_together={("season", "week_number")},
        ),
    ]
