# Generated by Django 5.2.3 on 2025-08-13 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_alter_offweek_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='scheduler.week'),
        ),
    ]
