# Generated by Django 5.2.3 on 2025-08-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_change_week_fk_to_protect'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration override for this level (falls back to season default if not set)', null=True),
        ),
        migrations.AddField(
            model_name='season',
            name='slot_duration_minutes',
            field=models.PositiveIntegerField(default=70, help_text='Duration of each game slot in minutes (includes game time + halftime)'),
        ),
    ]
