# Generated by Django 5.2.3 on 2025-08-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_level_slot_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offweek',
            name='description',
            field=models.TextField(default='No games scheduled', help_text="Description of what's happening this week (e.g., 'Charity Tournament', 'Holiday Break')"),
        ),
        migrations.AddField(
            model_name='offweek',
            name='has_basketball',
            field=models.BooleanField(default=False, help_text='Whether basketball events are happening this week (affects styling)'),
        ),
        migrations.AddField(
            model_name='offweek',
            name='title',
            field=models.CharField(choices=[('off_week', 'Off Week'), ('tournament', 'Tournament'), ('other', 'Other')], default='off_week', help_text='Type of non-league week', max_length=20),
        ),
    ]
