# Generated by Django 5.2.3 on 2025-08-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_offweek_description_offweek_has_basketball_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offweek',
            name='title',
            field=models.CharField(default='Off Week', help_text='Title of this non-league week', max_length=100),
        ),
    ]
