# Generated by Django 5.2.3 on 2025-08-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_alter_offweek_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='offweek',
            name='end_time',
            field=models.TimeField(blank=True, help_text='End time for events this week', null=True),
        ),
        migrations.AddField(
            model_name='offweek',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Start time for events this week', null=True),
        ),
    ]
